### ISSUE TITLE
When executing `frida-list-apps`, errors found

### ISSUE THREAD

**Issue by illnino** [dweinstein/node-frida-contrib#2]
## Problem

When executing `frida-list-apps`, I got errors.

## ENV

Mac 10.11.6
frida 10.0.1
node 4.5.0, 4.6.2, 6.10.3

## Reproduction Steps

1. Connect devices to Mac
2. Run command - `frida-list-apps`

### v6.10.3

```bash
➜  ~ node -v
v6.10.3

➜  ~ frida-list-apps
node: bad option: --harmony_arrow_functions
```

``` v4.6.2
➜  ~ node -v
v4.6.2
➜  ~ frida-list-apps
/Users/its/.nvm/versions/node/v4.6.2/lib/node_modules/frida-contrib/node_modules/debug/src/debug.js:48
    hash  = ((hash << 5) - hash) + namespace.charCodeAt(i);
                                             ^

TypeError: namespace.charCodeAt is not a function
    at selectColor (/Users/its/.nvm/versions/node/v4.6.2/lib/node_modules/frida-contrib/node_modules/debug/src/debug.js:48:46)
    at createDebug (/Users/its/.nvm/versions/node/v4.6.2/lib/node_modules/frida-contrib/node_modules/debug/src/debug.js:120:17)
    at Object.<anonymous> (/Users/its/.nvm/versions/node/v4.6.2/lib/node_modules/frida-contrib/config/index.js:15:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/its/.nvm/versions/node/v4.6.2/lib/node_modules/frida-contrib/bin/list-apps:5:12)
➜  ~
```

``` v4.5.0
➜  ~ node -v
v4.5.0
➜  ~ frida-list-apps
/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/frida-contrib/node_modules/debug/src/debug.js:48
    hash  = ((hash << 5) - hash) + namespace.charCodeAt(i);
                                             ^

TypeError: namespace.charCodeAt is not a function
    at selectColor (/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/frida-contrib/node_modules/debug/src/debug.js:48:46)
    at createDebug (/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/frida-contrib/node_modules/debug/src/debug.js:120:17)
    at Object.<anonymous> (/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/frida-contrib/config/index.js:15:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/frida-contrib/bin/list-apps:5:12)
➜  ~
```

**Comment by radare** [comment]
Can you try with node LTS (v6)?

**Comment by illnino** [comment]
I think i am already using the latest lts

```
➜  nvm ls-remote --lts | grep Latest
         v4.8.3   (Latest LTS: Argon)
        v6.10.3   (Latest LTS: Boron)
```


```
➜  ~ node -v
v6.10.3

➜  ~ frida-list-apps
node: bad option: --harmony_arrow_functions
```

Error - `node: bad option: --harmony_arrow_functions`

**Comment by dweinstein** [comment]
I haven't used this code for a while, but if you remove the --harmony* option from the top of the JS file it should get rid of this error

**Comment by illnino** [comment]
May I know how should I remove it?

I installed the package with `npm install -g`.
________________________________

**Comment by dweinstein** [comment]
```sh
$ git clone git@github.com:dweinstein/node-frida-contrib.git
$ cd node-frida-contrib && npm i
$ vim bin/list-apps 

edit the first line.
```

I'll probably just fix it in a few min after I get out of some meetings.
